#!/bin/sh
/usr/bin/docker run --net=host --rm -v /opt/pidalio/kube/kubelet/scripts/ceph/resolv.conf:/etc/resolv.conf:ro -v /opt/pidalio/kube/kubelet/scripts/ceph/keys/:/etc/ceph ceph/base:tag-build-master-hammer-ubuntu-16.04 ceph "$@"
